### ISSUE TITLE
Iron golems not spawning

### ISSUE THREAD

**Issue by jnijland** [tr7zw/YAPFA#386]
**Expected behavior**
I used to have my BentoBox Bskyblock server running Tuinity. I found this fork, so I copied that server and changed the server from Tuinity 1.16.5 to Yatopia 1.16.5. 

Suddenly, all iron golem farms on Skyblock stopped working. I was expecting golems to spawn like normal, but they don't. 

**Observed behavior**
No iron golems are spawning at all.

**Steps to reproduce (if known)**
Create a Yatopia server with BentoBox skyblock plugin and create a iron golem farm:
![image](https://user-images.githubusercontent.com/9889834/106660407-3e571800-65a0-11eb-8b84-9182afe8612c.png)

**Installed plugins**
![image](https://user-images.githubusercontent.com/9889834/106660261-0a7bf280-65a0-11eb-89fe-7eff647fcc2a.png)

**Version**
![image](https://user-images.githubusercontent.com/9889834/106660292-15cf1e00-65a0-11eb-9b54-5d83962cf277.png)

**Additional context**
As I said, I was running Tuinity 1.16.5 and updated to Yatopia 1.16.5. Everything was working fine on Tuinity 1.16.5.

**Comment by Titaniumtown** [comment]
Did you change anything in `purpur.yml` relating to villagers or iron golems?

**Comment by jnijland** [comment]
> Did you change anything in `purpur.yml` relating to villagers or iron golems?

I didn't @Titaniumtown, should I?

**Comment by tommasobenatti** [comment]
I tested personally and the iron golems are spawning with build 18

**Comment by jnijland** [comment]
Did you try with Bentobox Bskyblock, @tommasobenatti?

Maybe it's a Bentobox Bskyblock problem, but that seems so strange since it was working with Tuinity 1.16.5....

**Comment by jnijland** [comment]
One of my players made another farm, slightly different design, it worked on Tuinity for them... 
![image](https://user-images.githubusercontent.com/9889834/106672185-f63ff180-65af-11eb-81f9-351cf57f6e39.png)

This also doesn't work. Could it be a setting in one off the config files? I do have per-player mob spawning enabled... 🤔 I must admit I'm getting a bit lost in all the config files 😋

**Comment by tommasobenatti** [comment]
> Did you try with Bentobox Bskyblock, @tommasobenatti?
> 
> Maybe it's a Bentobox Bskyblock problem, but that seems so strange since it was working with Tuinity 1.16.5....

I tested it on a Survival server

**Comment by jnijland** [comment]
> > Did you try with Bentobox Bskyblock, @tommasobenatti?
> > Maybe it's a Bentobox Bskyblock problem, but that seems so strange since it was working with Tuinity 1.16.5....
> 
> I tested it on a Survival server

I suppose it's a Bentobox Bskyblock setting somehow then @tommasobenatti ... Still strange how it did work on a 'normal' tuinity 1.16.5. then. Thanks for testing.

**Comment by tommasobenatti** [comment]
Try with Purpur

**Comment by jnijland** [comment]
Apparently it was a changed BentoBox configuration option that was not well-documented. The issue is solved and it had nothing to do with Yatopia. In case anybody found this through Google, this is what I've done to fix the issue with mobs not spawning on Bentobox: 

Edit file ```/plugins/bentobox/addons/bskyblock/config.yml```

```yaml
  spawn-limits:
    # Spawn limits. These override the limits set in bukkit.yml
    # If set to a negative number, the server defaults will be used
    # Added since 1.11.2.
    monsters: 20
    # Added since 1.11.2.
    animals: 8
    # Added since 1.11.2.
    water-animals: 5
    # Added since 1.11.2.
    ambient: 5
    # Setting to 0 will disable animal spawns, but this is not recommended. Minecraft default is 400.
    # A negative value uses the server default
    # Added since 1.11.2.
    ticks-per-animal-spawns: 1
    # Setting to 0 will disable monster spawns, but this is not recommended. Minecraft default is 400.
    # A negative value uses the server default
    # Added since 1.11.2.
    ticks-per-monster-spawns: 1
  ```

Normally they'd advise you to use -1 on all the values here, but that seems to completely disrupt mob and animal spawning.
