### ISSUE TITLE
Odd chunk loading behavior with dev/threaded-worldgen

### ISSUE THREAD

**Issue by mibby** [tr7zw/YAPFA#397]
**Expected behavior**
Chunk loading to behave like main branch Yatopia.

**Observed behavior**
Chunk loading after teleporting seems to load black un-rendered chunks, then they slowly come in a second or two afterwards. Reproducible every time, every teleport, with the same loading behavior in the same area.

**Steps to reproduce (if known)**
1. Teleport to a location.
2. Teleport back to a new location. 

i.e.

1. Teleport to player or home in ``world``.
2. Teleport to spawn with ``/spawn`` in the separate dimension ``spawn`` world.

**Installed plugins**
Not relevant.

**Version**
Yatopia version git-Yatopia-dev/threaded-worldgen-"885bddf" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
(Action build 1368)

**Additional context**
This happens only with the dev/threaded-worldgen branch builds. It is noticeably slow and takes seconds. I was able to screenshot every interval when chunks loaded.

https://imgur.com/a/ymByDa3

With Yatopia ver/1.16.5 (action build 1370), chunks load immediately and all at once. It's impossible to screenshot "loading intervals" since the entire view is loaded in less than a second.

**Comment by ishland** [comment]
This send rate is limited by Tuinity new chunkloading system. Increasing the numbers in tuinity.yml solves this for me

**Comment by mibby** [comment]
It was occurring with both the old & new tuinity chunk values. What values would bring it back up to main branch speed / loading behavior? I'd rather have vanilla Paper chunk loading that's instant than artificially limiting loading for bandwidth/latency reasons since speed is all players see or care about. Black un-rendered chunks every teleport is an awful experience.

```
player-chunks:
  enable-mc162253-workaround: true
  target-chunk-send-rate: -45.0
  enable-frustum-priority: false
  autoconfig-send-distance: true
  min-load-radius: 3
  max-concurrent-sends: 3.0
  max-concurrent-loads: 5.0
```

```
player-chunks:
  enable-mc162253-workaround: true
  target-chunk-send-rate: -25.0
  enable-frustum-priority: false
  autoconfig-send-distance: true
  min-load-radius: 2
  max-concurrent-sends: 1.0
  max-concurrent-loads: 2.0
```

**Comment by ishland** [comment]
raise `target-chunk-send-rate` to a high value like `-160`
also raise `max-concurrent-sends` and `max-concurrent-loads`

If you have any further questions, feel free to join our [Discord Server](https://discord.io/YatopiaMC)

**Comment by Titaniumtown** [comment]
> enable-mc162253-workaround: true

I would recommend disabling that as (according to spottedleaf) it can cause some strange networking issues.

>   max-concurrent-sends: 1.0
  max-concurrent-loads: 2.0

If you want faster chunk loading, put that higher to like:

>   max-concurrent-sends: 6.0
  max-concurrent-loads: 10.0

Just experiment around with it and see what configs are the best for you.

**Comment by mibby** [comment]
Sure, thanks. I'll give it a try and hop on the discord server for any future concerns.

**Comment by Titaniumtown** [comment]
I'll close this since it seems the issue is with configs.

**Comment by mibby** [comment]
I still seem to be experiencing the initial chunk teleport being slower and displaying black un-loaded chunks in a short radius until it sends the new chunks a second later. It is distinctly and noticeably slower every teleport. I believe there is a breaking change somewhere causing this regression from the main branch since main branch loads immediately without lag or visual anomalies. :( Unless tuinity's patch just makes it worse.

![link](https://i.imgur.com/uR5f8SD.png)

Tried with;

```
player-chunks:
  enable-mc162253-workaround: false
  target-chunk-send-rate: -160.0
  enable-frustum-priority: false
  autoconfig-send-distance: true
  min-load-radius: 2
  max-concurrent-sends: 6.0
  max-concurrent-loads: 10.0
```

&

```
player-chunks:
  enable-mc162253-workaround: false
  target-chunk-send-rate: -160.0
  enable-frustum-priority: false
  autoconfig-send-distance: true
  min-load-radius: 8
  max-concurrent-sends: 4.0
  max-concurrent-loads: 6.0
```

How it normally looks once loaded.
![link2](https://i.imgur.com/Fk1SkRD.png)
